---
title: "Subsetting metadata for case classification" 
output: html_notebook
---

```{r}
library(readstata13)

# Read bloomberg metadata
bloomberg <- read.dta13('~/Desktop/QMSSWork/CaseClassifier/data/BloombergVOTELEVEL_Touse.dta')
```

```{r}
# Read training data labels 
convote <- read.dta13('~/Desktop/QMSSWork/CaseClassifier/data/caseid_convote.dta')
training_data <- subset(convote, convote %in% c(-1, 1))
```

```{r}
library(dplyr)
library(tidyr)

# Filter for first judge listed 
bloomberg_author <- bloomberg %>% filter(j == Writer)

# Subset bloomberg for training cases only 
bloomberg_training <- subset(bloomberg_author, caseid %in% training_data$caseid)

# Merge bloomberg_training with training labels 
training <- merge(bloomberg_training, training_data, by = 'caseid', all.x = TRUE)
```


# Explore judges and conservative label 

```{r}
# Count of authoring judges in the training set 
length(unique(training$Author))
```

```{r}
# Number of cases written per judge 
num_cases_written <- as.data.frame(table(training$Author)) 

# Subset conservative and liberal cases 
conservative <- subset(training, convote == 1)
liberal <- subset(training, convote == -1)

num_conservative_written <- as.data.frame(table(conservative$Author))

num_liberal_written <- as.data.frame(table(liberal$Author))
head(num_liberal_written)

num_cases_written <- merge(num_cases_written, num_conservative_written, 
                           by = 'Var1', all.x = TRUE, fill=0)
num_cases_written <- merge(num_cases_written, num_liberal_written, 
                           by = 'Var1', all.x = TRUE, fill=0)
colnames(num_cases_written) <- c('Author', 'TotalCases', 'Conservative', 'Liberal')

num_cases_written <- num_cases_written %>% 
  replace_na(list(Conservative=0, Liberal=0)) %>% 
  mutate(PctConservative = Conservative / TotalCases) %>% 
  arrange(desc(PctConservative), desc(TotalCases))


head(num_cases_written)
```

```{r}
library(ggplot2)

# Plot number of cases written by percentage of cases which are conservative 
g <- ggplot(data=num_cases_written, aes(x=TotalCases, y=PctConservative)) + 
  geom_point() + 
  ggtitle('Total Cases Written vs. Percentage of Conservative Cases')
g
```

```{r}
# Plot histogram of percentage of conservative cases 

g_hist <- ggplot(data=num_cases_written, aes(x=PctConservative)) + 
  geom_histogram() + 
  ggtitle('Percentage Conservative Cases by Judge')
g_hist
```


# Check topic distribution across judges 

```{r}
judges_topic <- training %>% 
  group_by(Author) %>% 
  summarize(n_distinct(geniss1))

hist(judges_topic$`n_distinct(geniss1)`)
```

# Count of cases by topic 

```{r}
num_per_topic <- as.data.frame(table(training$geniss1)) 
num_per_topic_conservative <- as.data.frame(table(conservative$geniss1))
num_per_topic_liberal <- as.data.frame(table(liberal$geniss1))

num_per_topic <- merge(num_per_topic, num_per_topic_conservative, 
                           by = 'Var1', all.x = TRUE, fill=0)
colnames(num_per_topic) <- c('Var1', 'Total', 'Conservative')
num_per_topic <- merge(num_per_topic, num_per_topic_liberal, 
                           by = 'Var1', all.x = TRUE, fill=0)
colnames(num_per_topic) <- c('Var1', 'Total', 'Conservative', 'Liberal')
num_per_topic
```

# Split training / validation / test by judge

There are 11,445 training cases and 780 judges 

Aim to have a 80% (9156 cases, 624 judges) train, 10% (1145 cases, 78 judges) validation, 10% (1144 cases, 78 judges) test 

```{r}
set.seed(2) 

judges <- unique(training$Author)

train_idx <- sample(seq(length(judges)), size = (780 * 0.8)) 
train_judges <- judges[train_idx]
train_cases <- subset(training, Author %in% train_judges)
paste('Num Training Cases:', length(train_cases$caseid))

validation_and_test <-  subset(training, !(Author %in% train_judges)) 
num_validation <- length(validation_and_test$caseid) / 2 
validation_cases <- validation_and_test[seq(num_validation), ]
test_cases <- validation_and_test[-seq(num_validation), ]
paste('Num Validation Cases:', length(validation_cases$caseid))
paste('Num Test Cases:', length(test_cases$caseid))
```


# Check topic distribution in validation 

```{r}
num_per_topic <- as.data.frame(table(validation_cases$geniss1))
conservative_validation <- subset(validation_cases, convote == 1)
liberal_validation <- subset(validation_cases, convote == -1)
num_per_topic_conservative <- as.data.frame(table(conservative_validation$geniss1))
num_per_topic_liberal <- as.data.frame(table(liberal_validation$geniss1))

num_per_topic <- merge(num_per_topic, num_per_topic_conservative, 
                           by = 'Var1', all.x = TRUE, fill=0)
colnames(num_per_topic) <- c('Var1', 'Total', 'Conservative')
num_per_topic <- merge(num_per_topic, num_per_topic_liberal, 
                           by = 'Var1', all.x = TRUE, fill=0)
colnames(num_per_topic) <- c('Var1', 'Total', 'Conservative', 'Liberal')
num_per_topic
```

# Save sets to csv 

```{r}
write.csv(train_cases, '~/Desktop/QMSSWork/CaseClassifier/data/processed_data/training_cases.csv')

write.csv(validation_cases, '~/Desktop/QMSSWork/CaseClassifier/data/processed_data/validation_cases.csv')


write.csv(test_cases, '~/Desktop/QMSSWork/CaseClassifier/data/processed_data/test_cases.csv')
```



